- src/lib.rs
I'm not sure if this is a complete solution, but I think it's moving in the right direction.
- DotenvError is replacing the ParseError that I had used in https://github.com/slapresta/rust-dotenv/pull/2
- I tried to unify the possible errors to the new DotenvError, using the From<T> trait
- try! is used instead of unwrap to avoid unnecessary panics.
> Improve error handling

- README.md
- src/lib.rs
Using the PWD env var we should be able to set the env in the root directory.  I think this is a better default than where the executable file is.  What do you guys think?
Good work on the package by the way.  :smile:
> Set the default .env location to the absolute path of the working directory

- Cargo.toml
Address #14 by limiting regex to versions less than 0.2 (the current version is 0.1.41).
> specify version range for regex dependency

- README.md
- src/lib.rs
This change makes it so `from_filename()` (and consequently
`dotenv()`) first attempts to load from the working directory.
Then if the file is not found, it tries again in the parent,
repeating until the file is found or the top-level directory is
reached.  This is a superset of the directories checked in
previous versions.
Closes #18
> Change from_filename() to check parent directories

- README.md
- dotenv_codegen/Cargo.toml
- dotenv_codegen/src/dotenv_macro.rs
- dotenv_codegen/src/lib.rs
- dotenv_macros/Cargo.toml
- dotenv_macros/src/lib.rs
The meat of this macro is absurdly simple, most of the code here is just
machinery for use on both stable and nighlty.
The macro is identical to the `env!` macro, but it calls
`dotenv::dotenv()` for you at compile time. If a `.env` file is found,
but fails to parse, the code will not compile. If a `.env` file is not
found, the behavior is simply that of `env!`, as `.env` files are meant
to be optional.
`dotenv_codegen` and `dotenv_macros` are separate crates, because we
need the format to be `rlib` on stable, but `dylib` on nightly
(specifying both can cause some weird issues when building downstream).
This doesn't include tests for the macro, as it would require jumping
through some hoops to get a simple test working, but I've tested this on
Diesel and it works great. A test can easily …
> Implement the `dotenv!` macro

- src/lib.rs
This solves the main issue outlined on #24, but it does not separate `FileNotFound` errors from other `Io` errors.
/cc @sgrif
> Seek parent only on IO errors

- dotenv_codegen/src/dotenv_macro.rs
This function was moved and made private within Rust. While it sucks to
basically copy the impl here, it's a pretty stable item and I don't
expect it to change.
> Inline `expand_env`

- dotenv_codegen/Cargo.toml
A new version has been released, which does not break our build
> Bump syntex version

- dotenv_codegen/Cargo.toml
I've loosened the constraints to a range, but ultimately that's not
terribly helpful since Cargo doesn't let you specify transitive
dependency versions, and it'll always resolve to the latest version. As
such, I've bumped the major here so that code depending on `^0.7.2`
will continue to compile.
> Bump syntex (again)

- dotenv_codegen/Cargo.toml
- dotenv_codegen/src/dotenv_macro.rs
- dotenv_macros/Cargo.toml
@slapresta Just wanted to ping you before I merge/release this. We were affected by actual breakage, which means I need to bump the version of codegen and macros to 0.9.0. I know you had mentioned maybe wanting to keep them in sync, but I'd like to argue for separating them so that we don't have to bump the version on the main crate unnecessarily. Since codegen/macros are entirely dealt with at compile time, which version of dotenv they use underneath is actually not relevant, and can be separate from the application.
> Update codegen for breaking changes in libsyntax

- .travis.yml
It's pretty common for Rust libraries to have CI testing. This will run both the tests in src/lib.rs as well as the ones in test/src/main.rs. Of course, someone will have to actually enable the integration on travis-ci.
> Integrate Travis

- dotenv_codegen/src/dotenv_macro.rs
The newest nightly builds have some changes replacing InternedString with Symbol, which caused the macros not to build. For some reason that is beyond me, it wouldn't let it build when directly built at the `dotenv_codegen` directory ("can't find syntax::symbol"), but it builds and actually fixes the build when built as a part of the `dotenv_macros`.
> Updated syntax

- Cargo.toml
- src/lib.rs
The syntax changes in `regex 0.2` don't affect `rust-dotenv` which means this update is pretty straight-forward.
(closes #55)
> Bump regex to 0.2

- Cargo.toml
- src/lib.rs
This PR introduces a dependency on the [error_chain](https://crates.io/crates/error-chain) and [derive_error_chain](https://crates.io/crates/derive-error-chain) crates to implement Error handling. Basically, this just reduces some error-handling-related boilerplate.
The first patch in the PR is actually from @Nashenas88 #51 (sorry if inappropriate to include in my PR).
Obviously, this is really a "dependency choice" style change. If there is no interest in introducing this dependency, I would be interested in at least getting #51 merged as it does the actual work of improving downstream interaction with this crate.
> Use error_chain/derive_error_chain for Error handling & transformation

- Cargo.toml
- src/lib.rs
At the moment the `dotenv` crate forces the feature `backtrace` of `error-chain` on. This PR makes it optional, allowing users to opt out from backtrace-including errors when they are using `dotenv`.
The backtraces are still, as of the default, on, like they used to be.
> Made backtraces optional.

- Cargo.toml
- src/lib.rs
`derive-error-chain`: proc macro `error_chain` has been renamed to `ErrorChain`.
> bump error-chain to 0.11.0

- .travis.yml
This PR contains a quick fix to stop Travis builds from failing.
It seems that, starting on cargo 0.23, running `cargo test` will execute the tests on the `tests` folder. This is unfortunate, since our tests expect to be ran from the `tests` folder. This fixes the issue on Travis, by only running library and documentation tests when outside the `tests` folder.
A separate issue will be opened to address the fact that `cargo test` fails when ran unqualified on the root folder of the project, which is definitely concerning.
> Avoid testing `/tests` from outside its folder on Travis

- .travis.yml
- dotenv_codegen/.env
- dotenv_codegen/Cargo.toml
- dotenv_codegen/dotenv_codegen_impl/Cargo.toml
- dotenv_codegen/dotenv_codegen_impl/src/lib.rs
- dotenv_codegen/tests/basic_dotenv_macro.rs
This updates the 'syn' dependency of dotenv_codegen. Depends on #88.
Fixes #90.
> Update dotenv syn

- Cargo.toml
- src/errors.rs
- src/lib.rs
- src/parse.rs
Moves the line regex into a lazy static, so we only initialize it once per run. Also, since the regex should always compile, unwrap it and remove the corresponding enum error variant.
> Lazily initialize line regex

- src/find.rs
- src/lib.rs
For filename operations, it might be better to accept anything that is `AsRef<Path>` instead of limiting input to only `&str`or `&Path`.
As a bonus `directory` argument of `find()` function is not `mut` anymore.
> Use AsRef<Path> generic type parameter instead of &str or &Path

- README.md
Thanks for the nice tool.
I added a little note to README about how to install CLI command.
It's probably enough to close this issue: https://github.com/purpliminal/rust-dotenv/issues/104
> Add a note regarding CLI to README

- .travis.yml
This PR is in reference to https://github.com/purpliminal/rust-dotenv/issues/107#issuecomment-402331015 to add a build and a test run for `--no-default-features`.
> Add a build and a test run to travis for --no-default-features
